version: "2"

formatters:
  enable:
    - gofmt

linters:
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (*text/tabwriter.Writer).Write
        - (*text/tabwriter.Writer).Flush
